cd hoimetruyen-api && yarn
cd ../hoimetruyen-comic-site && yarn
cd ../hoimetruyen-mobile-site && yarn
cd ../hoimetruyen-account && yarn
cd ../hoimetruyen-admin && yarn
cd ../hoimetruyen-manager && yarn
cd ../hoimetruyen-evil && yarn
cd ../hoimetruyen-models && yarn
cd ../hoimetruyen-modules && yarn